version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      -
        image: circleci/python:2.7.14-stretch-browsers
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mkdir test-reports
            sudo pip install pipenv
            sudo pipenv install
            sudo pip install pytest
            sudo pip install mock
            sudo python setup.py install
            sudo pipenv run "pytest --junitxml=test-reports/junit.xml"
      - store_test_results:
          destination: test-reports
          path: test-reports
      - store_artifacts:
          destination: test-reports
          path: test-reports
