#!/usr/bin/env python
import argparse
import sys

from zeppelin_handy_helpers import Read, Check, Stop, Monitor


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--end_point', help='Specify Zeppelin API end_point',
                        required=True, type=str)
    parser.add_argument('--slack_end_point', help='Specify Slack Incoming Webhook',
                        required=True, type=str)
    parser.add_argument('--read', help='Show all notebook names and ids', action=Read, nargs='?', type=str)
    parser.add_argument('--check', help='Show all running paragraphs', action=Check, nargs=0)
    parser.add_argument('--stop', help='Stop all runnning paragraphs', action=Stop, nargs=0)
    parser.add_argument('--monitor', help='Monitor all running paragraphs', action=Monitor, nargs=0)

    if (len(sys.argv)) < 2:
        parser.print_help()
        sys.exit(1)
    else:
        parser.parse_args()


if __name__ == '__main__':
    main()
